
#settings
[fragiletorches]
	#Chance that a torch will break during a collision (checks on a tick while entity is inside torch)
	#Range: 0.0 ~ 1.0
	chancetobreak = 0.019999999552965164

	[fragiletorches.entities]

		[fragiletorches.entities.gentle]
			#List of 'gentle' entities that will never knock over any tagged torch
			list = ["minecraft:bat", "minecraft:boat", "minecraft:cat", "minecraft:ender_pearl", "minecraft:egg", "minecraft:horse", "minecraft:item", "minecraft:donkey", "minecraft:experience_orb", "minecraft:minecart", "minecraft:player", "minecraft:villager", "minecraft:wolf"]

