
mod_id=fragiletorches
curse_id=231800
curse_slug=fragile-torches
mod_version=1.0.2
mod_name=fragiletorches
mod_group_id=com.lothrazar.fragiletorches
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=

flib_version=0.1.0
flib_file=8022223


